export {
  cleanSuperAdminSourceDecks,
  isForbiddenSuperAdminSourceDeck,
  isRemovedSuperAdminOpticalDeck,
  FORBIDDEN_SUPER_ADMIN_SOURCE_DECKS,
  REMOVED_SUPER_ADMIN_OPTICAL_DECKS,
  RETIRED_SUPER_ADMIN_STATIC_FACT_DECKS,
  RETIRED_SUPER_ADMIN_RUSSIAN_MOTIVATION_DECKS,
  RETIRED_SUPER_ADMIN_CHRISTIAN_FACT_DECKS,
  RETIRED_SUPER_ADMIN_SOVIET_POSTER_DECKS,
} from "./super-admin-forbidden-source-decks.ts";
